services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - user-service

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8080"